language: node_js
node_js:
  - '10'
sudo: false
branches:
  only:
    - source
git:
  submodules: false
before_install:
  - export TZ=Asia/Taipei
  - npm install -g npm@next
  - npm install -g hexo-cli
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
before_script:
  - git config --global user.name 'Kevin Yang'
  - git config --global user.email 'chgc_kevin@hotmail.com'
  - sed -i'' "s~git@github.com:chgc/chgc.github.io.git~https://${DEPLOY_TOKEN}@github.com/chgc/chgc.github.io.git~"
    _config.yml
install:
  - npm i
script:
  - hexo clean
  - hexo generate
after_success:
  - hexo deploy
cache:
  directories:
    - node_modules
