language: node_js
node_js:
  - "6"
sudo: false
branches:
  only:
  - source
before_install:
- export TZ=Asia/Taipei
- npm install -g hexo-cli
before_script:
- git config --global user.name 'Kevin Yang'
- git config --global user.email 'chgc_kevin@hotmail.com'
- sed -i'' "s~git@github.com:chgc/chgc.github.io.git~https://${DEPLOY_TOKEN}@github.com/chgc/chgc.github.io.git~"
  _config.yml
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
cache:
  directories:
  - node_modules   
