language: node_js
sudo: false
branches:
  only:
  - source
before_install:
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name 'Kevin Yang'
- git config --global user.email 'chgc_kevin@hotmail.com'
- sed -i'' "s~git@github.com:chgc/chgc.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/chgc/chgc.github.io.git~"
  _config.yml
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
cache:
  directories:
  - node_modules
env:
  global:
    secure: crOQvIZjXD8QInBKhoTwgig54gnSZVZhwM3QA4cNp0SDKIPpDC0JVUEy+dPGGbS9AyYkKQXkbtqg3a+soT5LeY2aMleGA5pvt6ygGfYUgjzWmQyHABtA6+g+EwZIzjV0oTZJpMRTzm5bjdjKBu1o1YVA3VReMp4ROFI+rKCPXjfMizR8JENB0gAKQaf9w0jX2IdbsJ8X7mIAAZ5G//2d8Q2ng1QvmdAvgZui2lOF0WC1C3Kb6TCcxko5xgQ5l50sukkJ8t4Yx8RjoMQYW0OQOXIPpSysz0BMzn17dy2A6wo+nb1FY2ld2ietxrj0jwxl98lJdCXOgGTjIE04gHCR2w49HKRep94pVtCE+PenBJEqyNMFHn0stAYG9YYQOANdkuRqQIRPwX96wJlDWD4Iz7m1Di7mwdUUcOUYOfT0q3i+OEFBQYd64h1OdHBxWVaZJCpVUai92v3+0LxNhvqY9L8r0Z2gCPA+3WRrD9QJYNvoQFLEtdDv9e3Dv2D0YBATjae45vMlfb3GVNARdnuJI45OA9VKIfPTX7lw4DnB/Z8iyV/Ou2Of+yJPXlzLvpPz+OfQRETRzKLdvW671EtZYTEGkjqzJdihNI2zPlL5RdCkGWZBUtXg1O8VT8LpMTqx3MyHM6NY64l96TbxPvbFPk8ux/Qet6occlHOe+9fkeg=
